### ISSUE TITLE
Class Class ifteam\UUIDAuth\auth\AuthDataLoader not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

### ISSUE THREAD

**Issue by ghost** [HmHmmHm/UUIDAuth#2]
[Server thread/CRITICAL]: ClassNotFoundException: "Class ifteam\UUIDAuth\auth\AuthDataLoader not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by ghost** [comment]
Please fix... I need this plugin. Whoever is making this Is doing the world a huge favor.

**Comment by HmHmmHm** [comment]
thsi plug-in not yet finished programming, and i think it will be cancelled for developing

**Comment by ghost** [comment]
No. NO!
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO!!!!!!!!!!!!!!!!!!!!!

**Comment by ghost** [comment]
PLEASE MAKE IT WORK!!!! ILL DONATE

**Comment by ghost** [comment]
I'l donate. Please make this work.

**Comment by HmHmmHm** [comment]
oh... bro... if could be i'll be make next month.. save your money

**Comment by ghost** [comment]
Thank you.

**Comment by ghost** [comment]
You have no idea how grateful I am to you! :D

**Comment by ghost** [comment]
Once you make this, people will start implementing this with the the simple
auth or the more advanced auth
